//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerPatient
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> StatusPatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual StatusPatient StatusPatient { get; set; }
        public virtual User User { get; set; }
    }
}
